// flow-typed signature: eb1c7eae159714af229c6b0a2112bf74
// flow-typed version: <<STUB>>/type-name_v^2.0.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'type-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'type-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'type-name/build/type-name' {
  declare module.exports: any;
}

// Filename aliases
declare module 'type-name/build/type-name.js' {
  declare module.exports: $Exports<'type-name/build/type-name'>;
}
declare module 'type-name/index' {
  declare module.exports: $Exports<'type-name'>;
}
declare module 'type-name/index.js' {
  declare module.exports: $Exports<'type-name'>;
}
